# Basket option implementation with Bachelier model CV

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pyfeng as pf

#import option_models as opt
from option_models import basket

In [3]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)

# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

In [4]:
cor_m

array([[1. , 0.5, 0.5, 0.5],
       [0.5, 1. , 0.5, 0.5],
       [0.5, 0.5, 1. , 0.5],
       [0.5, 0.5, 0.5, 1. ]])

In [5]:
print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket)

[1 0 0 0]
26.570984651213593


In [6]:
# Compare the price to normal model formula

norm1 = pf.Norm(sigma=40)
price_norm = norm1.price(strike, spot[0], texp, cp=1)
print(price_basket, price_norm)

26.570984651213593 26.570845957870503


In [7]:
# A trivial test case 2
# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 5
strike = 120

print( cor_m )

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_norm)

[[1.     0.9999 0.9999 0.9999]
 [0.9999 1.     0.9999 0.9999]
 [0.9999 0.9999 1.     0.9999]
 [0.9999 0.9999 0.9999 1.    ]]
26.57211110181949 26.570845957870503


In [8]:
# A full test set for basket option with exact price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100
price_exact = 28.0073695

In [9]:
weights, cor_m

(array([0.25, 0.25, 0.25, 0.25]), array([[1. , 0.5, 0.5, 0.5],
        [0.5, 1. , 0.5, 0.5],
        [0.5, 0.5, 1. , 0.5],
        [0.5, 0.5, 0.5, 1. ]]))

In [10]:
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_exact)

28.22782882893394 28.0073695


# [To Do] Basket option implementation based on BSM model
## Write the similar test for BSM

In [11]:
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket)

27.967309091912323


In [12]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)

[1 0 0 0]


In [13]:
bsm1 = pf.Bsm(sigma=vol[0])
price_bsm = bsm1.price(strike, spot[0], texp, cp=1)
print(price_basket, price_bsm)

28.51439365199859 28.713486748445934


# Spread option implementation based on normal model

In [14]:
# A full test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor = 0.5
cor_m = np.array([[1, cor], [cor, 1]])
texp = 1
strike = 0
price_exact = 8.5132252

In [15]:
# MC price based on normal model
# make sure that the prices are similar

np.random.seed(123456)
price_spread = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)
print(price_spread, price_exact)

8.317680907159142 8.5132252


# Spread option implementation based on BSM model

In [16]:
# Once the implementation is finished the BSM model price should also work
price_spread = basket.basket_price_mc(
    strike, spot, vol, weights, texp, cor_m, intr=intr, divr=divr, bsm=True)
price_spread

8.530935560352313

In [17]:
# You also test Kirk's approximation
kirk = pf.BsmSpreadKirk(vol, cor=cor, divr=divr, intr=intr)
price_kirk = kirk.price(strike, spot, texp)
print(price_kirk, price_spread)

8.513225229545505 8.530935560352313


# [To Do] Complete the implementation of basket_price_norm_analytic
# Compare the MC stdev of BSM basket prices from with and without CV

In [18]:
# The basket option example from above
spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 1, 1, 1])/4
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

In [19]:
### Make sure that the analytic normal price is correctly implemented
basket.basket_price_norm_analytic(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr)

19.330395569726363

In [20]:
# Run below about 100 times and get the mean and stdev

### Returns 2 prices, without CV and with CV 
price_basket = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)

In [21]:
np.array(price_basket)

array([22.29061434, 22.23100108])

In [22]:
price_basket_samples=np.zeros((100,2))
for i in range(0,100):
    price_basket = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)
    price_basket_samples[i] = np.array(price_basket)
price_basket_samples

array([[21.50624121, 21.71505089],
       [21.82505954, 21.91242789],
       [22.65707968, 22.13654032],
       [20.7364052 , 20.96767151],
       [22.71189745, 22.14791584],
       [22.32550832, 22.24514918],
       [21.6220785 , 21.87382803],
       [22.05725589, 22.04073523],
       [20.99303077, 21.20736008],
       [21.62588623, 21.66001515],
       [22.43737671, 22.28985801],
       [20.83486301, 21.14308916],
       [22.61564013, 22.20288488],
       [21.46547001, 21.68607793],
       [20.73728337, 21.26018725],
       [21.56259731, 21.39123322],
       [22.5974596 , 22.0928226 ],
       [23.43511734, 22.60681833],
       [21.65004262, 21.58358185],
       [22.48028344, 22.19252486],
       [21.45742879, 21.68456907],
       [22.09886569, 21.98082431],
       [21.79379744, 21.74328529],
       [21.2679245 , 21.29993419],
       [21.78090238, 21.80955696],
       [21.39152615, 21.73240493],
       [23.30322761, 22.45795316],
       [21.42455583, 21.50223872],
       [21.62490382,

In [23]:
np.mean(price_basket_samples,axis=0)

array([21.79150384, 21.7813311 ])

In [24]:
np.std(price_basket_samples,axis=0)

array([0.60778702, 0.3465952 ])